name: CI-CD Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'data/**'
      - 'Dockerfile'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest -q

  train_register_build:
    needs: test
    runs-on: ubuntu-latest
    env: # 👇 MLflow + DagsHub credentials
      MLFLOW_TRACKING_URI: https://dagshub.com/Tsravyareddy2002/my-first-repo.mlflow
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      MLFLOW_EXPERIMENT: iris_experiment
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install deps
        run: pip install -r requirements.txt

      # (Optional) Set up DVC if you want to pull datasets from DagsHub
      # - name: Install DVC
      #   run: pip install dvc

      # - name: Pull data with DVC
      #   run: dvc pull

      - name: Generate dataset
        run: python src/make_dataset.py

      - name: Train model
        run: python src/train.py --n-estimators 100

      - name: Evaluate model
        run: python src/evaluate.py

      - name: Register model
        run: python src/register_model.py --threshold 0.90

  docker_build_push:
    needs: train_register_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/iris-api:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/iris-api:latest
